import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";
import AuthProvider from "@/context/AuhtProvider";
import { EdgeStoreProvider } from "@/context/EdgeStoreProvider";
import { Toaster } from "@/components/ui/toaster";
import { cookies } from "next/headers";
import { verifyToken } from "@/lib/utils";
import User from "@/models/user";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user;
  const token = cookies().get("jwt")?.value;

  if (!token) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <EdgeStoreProvider>
            <AuthProvider>
              <Navbar />
              {children}
            </AuthProvider>
            <Footer />
          </EdgeStoreProvider>
          <Toaster />
        </body>
      </html>
    );
  }
  const jwtPayload = verifyToken(token);
  let userData;
  if (jwtPayload) {
    try {
      user = await User.findById(jwtPayload.sub);
      userData = JSON.parse(JSON.stringify(user));
    } catch (error) {
      console.log(error);
    }
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <EdgeStoreProvider>
          <AuthProvider userData={userData}>
            <Navbar />
            {children}
          </AuthProvider>
          <Footer />
        </EdgeStoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
