import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";
import AuthProvider from "@/context/AuhtProvider";
import { EdgeStoreProvider } from "@/context/EdgeStoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EdgeStoreProvider>
          <AuthProvider>
            <Navbar />
            {children}
          </AuthProvider>
          <Footer />
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
