import type { Metadata } from "next";
import "@/app/globals.css";
import SideNav from "@/components/shared/SideNav";

export const metadata: Metadata = {
  title: "DashBord",
  description: "Generated by create next app",
};

export default function DashbordLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="relative">
      <SideNav />
      {children}
    </section>
  );
}
